networks:
  factory-network:
  
services:

  machine-service:
    profiles:
      - machine

    build:
      context: /deployment-manager/deployment-workspace/machine-service

    image: machine-service:1.0

    networks:
      - factory-network

    ports:
      - "8001:8000"

  maintenance-service:
    profiles:
      - maintenance

    build:
      context: /deployment-manager/deployment-workspace/maintenance-service

    image: maintenance-service:1.0

    networks:
      - factory-network

    ports:
      - "8002:8000"

